use serde::{Deserialize, Serialize};

#[repr(i32)]
#[derive(Copy, Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum Activity {
    Reset = 0,
    Idle = 1,
    Guard = 2,
    Walk = 3,
    Run = 4,
    Fly = 5,
    Swim = 6,
    Hop = 7,
    Leap = 8,
    Fall = 9,
    Land = 10,
    StrafeLeft = 11,
    StrafeRight = 12,
    RollLeft = 13,
    RollRight = 14,
    TurnLeft = 15,
    TurnRight = 16,
    Crouch = 17,
    CrouchIdle = 18,
    Stand = 19,
    Use = 20,
    Signal1 = 21,
    Signal2 = 22,
    Signal3 = 23,
    Twitch = 24,
    Cower = 25,
    SmallFlinch = 26,
    BigFlinch = 27,
    RangeAttack1 = 28,
    RangeAttack2 = 29,
    MeleeAttack1 = 30,
    MeleeAttack2 = 31,
    Reload = 32,
    Arm = 33,
    Disarm = 34,
    Eat = 35,
    DieSimple = 36,
    DieBackward = 37,
    DieForward = 38,
    DieViolent = 39,
    BarnacleHit = 40,
    BarnaclePull = 41,
    BarnacleChomp = 42,
    BarnacleChew = 43,
    Sleep = 44,
    InspectFloor = 45,
    InspectWall = 46,
    IdleAngry = 47,
    WalkHurt = 48,
    RunHurt = 49,
    Hover = 50,
    Glide = 51,
    FlyLeft = 52,
    FlyRight = 53,
    DetectScent = 54,
    Sniff = 55,
    Bite = 56,
    ThreatDisplay = 57,
    FearDisplay = 58,
    Excited = 59,
    SpecialAttack1 = 60,
    SpecialAttack2 = 61,
    CombatIdle = 62,
    WalkScared = 63,
    RunScared = 64,
    VictoryDance = 65,
    DieHeadshot = 66,
    DieChestshot = 67,
    DieGutshot = 68,
    DieBackshot = 69,
    FlinchHead = 70,
    FlinchChest = 71,
    FlinchStomach = 72,
    FlinchLeftArm = 73,
    FlinchRightArm = 74,
    FlinchLeftLeg = 75,
    FlinchRightLeg = 76,
}

pub const ACTIVITIES: &[Activity] = &[
    Activity::Reset,
    Activity::Idle,
    Activity::Guard,
    Activity::Walk,
    Activity::Run,
    Activity::Fly,
    Activity::Swim,
    Activity::Hop,
    Activity::Leap,
    Activity::Fall,
    Activity::Land,
    Activity::StrafeLeft,
    Activity::StrafeRight,
    Activity::RollLeft,
    Activity::RollRight,
    Activity::TurnLeft,
    Activity::TurnRight,
    Activity::Crouch,
    Activity::CrouchIdle,
    Activity::Stand,
    Activity::Use,
    Activity::Signal1,
    Activity::Signal2,
    Activity::Signal3,
    Activity::Twitch,
    Activity::Cower,
    Activity::SmallFlinch,
    Activity::BigFlinch,
    Activity::RangeAttack1,
    Activity::RangeAttack2,
    Activity::MeleeAttack1,
    Activity::MeleeAttack2,
    Activity::Reload,
    Activity::Arm,
    Activity::Disarm,
    Activity::Eat,
    Activity::DieSimple,
    Activity::DieBackward,
    Activity::DieForward,
    Activity::DieViolent,
    Activity::BarnacleHit,
    Activity::BarnaclePull,
    Activity::BarnacleChomp,
    Activity::BarnacleChew,
    Activity::Sleep,
    Activity::InspectFloor,
    Activity::InspectWall,
    Activity::IdleAngry,
    Activity::WalkHurt,
    Activity::RunHurt,
    Activity::Hover,
    Activity::Glide,
    Activity::FlyLeft,
    Activity::FlyRight,
    Activity::DetectScent,
    Activity::Sniff,
    Activity::Bite,
    Activity::ThreatDisplay,
    Activity::FearDisplay,
    Activity::Excited,
    Activity::SpecialAttack1,
    Activity::SpecialAttack2,
    Activity::CombatIdle,
    Activity::WalkScared,
    Activity::RunScared,
    Activity::VictoryDance,
    Activity::DieHeadshot,
    Activity::DieChestshot,
    Activity::DieGutshot,
    Activity::DieBackshot,
    Activity::FlinchHead,
    Activity::FlinchChest,
    Activity::FlinchStomach,
    Activity::FlinchLeftArm,
    Activity::FlinchRightArm,
    Activity::FlinchLeftLeg,
    Activity::FlinchRightLeg,
];
